version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports: 
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
      - mysql

    networks:
      - haulmer_net

  mysql:
    image: mysql:8.0.28-oracle
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: haulmer
      MYSQL_ROOT_PASSWORD: secret

    ports:
      - 33060:3306
    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - haulmer_net

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html

    ports:
      - 9000:80
    networks:
      - haulmer_net
    
networks:
  haulmer_net:


